# Use an official Python runtime as the base image
FROM python:3.9-slim-bullseye
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*
# Set the working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app/ .

# Expose the port for the Flask service
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "main.py"]
